<?php

declare(strict_types=1);

namespace WindAndKite\Storyblok\Service;

/**
 * Builds Storyblok CLI v4 content migrations (`storyblok migrations run`) for renamed fields.
 *
 * Migrations copy, never move: the old field keeps its value, so production code reading it keeps
 * working until templates reading the new name (with a fallback) are deployed. They only fill the new
 * field when it's empty, so re-running them is harmless (the CLI skips bloks that don't change).
 */
class ComponentMigrationBuilder
{
    // Files carrying this marker are owned by the generator and may be rewritten or removed.
    public const MARKER = '@generated by bin/magento storyblok:schema:generate';
    public const FILE_SUFFIX = '.renames.js';

    /**
     * @param array<int, array{component: string, from: string, to: string}> $renames
     *
     * @return array<string, string> File name => JavaScript source.
     */
    public function build(array $renames): array
    {
        $byComponent = [];

        foreach ($renames as $rename) {
            $byComponent[$rename['component']][] = $rename;
        }

        $files = [];

        foreach ($byComponent as $component => $componentRenames) {
            $copies = array_map(
                static fn (array $rename) => sprintf(
                    "  // %1\$s -> %2\$s\n  if (isEmpty(block[%2\$s]) && !isEmpty(block[%1\$s])) {\n    block[%2\$s] = block[%1\$s];\n  }\n",
                    json_encode($rename['from']),
                    json_encode($rename['to'])
                ),
                $componentRenames
            );

            $files[$component . self::FILE_SUFFIX] = "// " . self::MARKER . " from @storyblok \"renamed_from\". Do not edit.\n"
                . "// Copies renamed fields (the old value is kept) and is safe to run more than once.\n"
                . "export default function (block) {\n"
                . implode("\n", $copies)
                . "\n  return block;\n}\n\n"
                . "function isEmpty(value) {\n"
                . "  if (value === undefined || value === null || value === '') return true;\n"
                . "  if (Array.isArray(value)) return value.length === 0;\n"
                . "  if (typeof value === 'object') {\n"
                . "    if (value.type === 'doc') return !value.content || value.content.length === 0;\n"
                . "    if (value.fieldtype === 'asset') return !value.filename;\n"
                . "    if (value.fieldtype === 'multilink') return !value.url && !value.cached_url && !value.email;\n"
                . "  }\n"
                . "  return false;\n"
                . "}\n";
        }

        ksort($files);

        return $files;
    }
}
