<?php

declare(strict_types=1);

/** @var \WindAndKite\Storyblok\Block\Block $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div <?= /** @noEscape */ $block->getBlokEditableAttributes() ?>>
    <?= $escaper->escapeHtml(__('Missing Template %1', $block->getStoryblokTemplate())) ?>

    <pre>
        <?= $escaper->escapeHtml(json_encode($block->getBlock()->getData(), JSON_PRETTY_PRINT)) ?>
    </pre>
</div>
