<?php
/**
 * This Template is not supposed to be used in a production environment,
 * this is used as a fallback where the correct Story template is missing.
 * This templates should be used as a guide to show what is achievable with the data at hand.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use WindAndKite\Storyblok\Block\Story;
use WindAndKite\Storyblok\Controller\Page\View;

/** @var Story $block */
/** @var Escaper $escaper */

/** @var array $story */
$story = $block->getStory();
?>
<?= $escaper->escapeHtml(__('Missing Template: %1', $block->getStoryblokTemplate())) ?>
<?= /** @noEscape */ $block->getContentHtml() ?>
<?php if ($storyblokList = $block->getChildBlock('storyblok.list')): ?>
    <?= /** @noEscape */ $storyblokList->setStory($this->getStory())->toHtml() ?>
<?php endif ?>
